# see https://www.appveyor.com/docs/build-configuration/#appveyoryml-and-ui-coexistence about relationship to configuration in UI
version: '{build}'
branches:
  except:
  - releases
skip_tags: true
clone_depth: 5
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    NODEJS_VERSION: 8
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    NODEJS_VERSION: 8
install:
- ps: Install-Product node $env:NODEJS_VERSION
- yarn --cache-folder=.cache/yarn --no-progress --pure-lockfile
cache:
- .cache/yarn
build: off
test_script:
- node_modules/.bin/gulp test!
on_success:
- 7z a coverage.zip coverage
- appveyor PushArtifact coverage.zip
