image: node:8-stretch
stages: [init, verify, deploy]
yarn:
  stage: init
  cache:
    paths: &cache_paths
    - .cache/yarn
  script:
  - &run_yarn
    yarn --cache-folder=.cache/yarn --pure-lockfile > /dev/null
lint:
  stage: verify
  cache: &pull_cache
    policy: pull
    paths: *cache_paths
  script:
  - *run_yarn
  - $(npm bin)/gulp lint
test:
  stage: verify
  cache: *pull_cache
  script:
  - *run_yarn
  - $(npm bin)/gulp test!
  artifacts:
    paths:
    - coverage/
release:
  stage: deploy
  only:
  - releases@antora/antora
  environment: releases
  script:
  - yarn global add lerna@$(node -p 'require("./lerna.json").lerna') > /dev/null
  - npm -v
  - scripts/release.sh
